### PR TITLE
Align Python API with JSON API

### PR DESCRIPTION
**Pull request by csingley**
Hey!  I really like the work you've done on this.  I'm expanding it, with the goal of achieving 100% API coverage bidirectionally (read/write).  Naturally this has necessitated some changes - I'm offering them to you if you're interested, but would understand if you'd prefer another direction.

Happy to discuss any of this if collaboration is of interest.

### CODE REVIEW

**Comment by ctalkington** [comment]
lots to review here. I do have a few immediate thoughts:

1) im trying to avoid the sense of promoting piracy. I feel while Sonarr can be used for such I only want to show legal uses. thus i wouldnt except any test fixture files containing currently copyrighted show informatiom. I used shows out of copyright like Andy Griffith because that would be legal use of Sonarr to download.

2) most likely id start by incorporating your work by integrating some of your decode/encoder logic and reorganizing the models a bit. There are some aspects i want to keep for yse with homeassistant which is the driving force of creating this.

**Comment by csingley** [comment]
1. The test fixtures I incorporated are the ones from Sonarr's API reference.  The docs and the examples contained therein aren't especially accurate, but I like coding to a spec.

2. May I suggest keeping a "core" API layer and then building atop it another layer containing the abstractions that work for your application... something akin to SQLAlchemy's declarative ORM, built on top of SQLAlchemy core.

I'm just trying to determine whether we've got enough common ground to work together on this - I generally prefer to avoid further fragmentation & wheel reinvention in the Python community - or if I should just fully split off the code base, get out of your hair, and do as I please.

Either way, you're welcome to use any of my work here in the same spirit in which you offered yours.  Thanks.

**Comment by ctalkington** [comment]
i dont think we have to split efforts. It may just take some iterations to get the best of both worlds here.

**Comment by csingley** [comment]
Don't sweat it, I'm just rewriting my own version.  I don't have any interest in async on the client side, but I do want to cover Radarr API, and start work on the upcoming Sonarr v3 API as well.  Let me know if you're feeling it on the collaboration, and we'll see if we can work something out.  Otherwise, strength to your arm, and thanks again for doing this.``

**Pull request closed without merging**
