### PR TITLE
Refactor to support arr

### PR DESCRIPTION
**Pull request by cliffordwhansen**
I know this is specifically for Sonarr, but since the other Arr apps use a similar API I refactored this to incorporate this. My use case is mostly HomeAssistant, and I am wanting to update the Radarr/Lidarr components so they can be configured via the user interface.

I plan to do Lidarr support next

### CODE REVIEW

**Comment by ctalkington** [comment]
thanks for starting this PR. I think we could combine efforts here. It's just a semi big change so I'm wondering the best way to merge and rollout without potential issues with sonarr. I also have some of my own planned refactoring that I revently applied to my rokuecp paackage and HA testS overhaul. I think it might make sense to rebrand the package so that everything can happen concurrently.

**Comment by cliffordwhansen** [comment]
I tried to make sure that this is all compatible with the current library, so no one will notice(tm) (someone always notice :-p)
Glad I could help, and I agree the name should change (only due to not being just sonarr)

**Comment by ctalkington** [comment]
@cliffordwhansen I recently came upon  https://github.com/tkdrob/aiopyarr which is used here (https://github.com/home-assistant/core/pull/65220) to update radarr and think I may stop supporting my package and any *arr work I was starting jn favor of it.

**Comment by cliffordwhansen** [comment]
@ctalkington the joys of opensource, there is always someone with more free time. The library you shared looks good.

**Pull request closed without merging**
